- name: Create A record for child domain in parent domain
  community.windows.win_dns_record:
    name: "{{lab.hosts[dc].hostname}}.{{item.split('.')[0]}}"
    type: "A"
    values:
      - "{{hostvars[dc].ansible_host}}"
    zone: "{{domain}}"
  vars:
    dc: "{{lab.domains[item].dc}}"
  loop: "{{ domains }}"
  when: domain == '.'.join(item.split('.')[1:])
