- name: Enable SMBV1 feature
  win_feature:
    name: SMB1Protocol
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: win_feature

- name: Reboot if feature requires it
  ansible.windows.win_reboot:
  when: win_feature.reboot_required