---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{ domain_name }}/data/"
  tags: 'data'

---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'

- name: WinScp for Robin
  hosts: srv02
  tasks:
    - name: Winscp on SRV2
      ansible.windows.win_shell: |
        reg import C:\winscp.reg