# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'


- name: "Prevent administrator from accessing the Credentials folder"
  hosts: srv01
  tasks:
    - name: "Change permissions"
      ansible.windows.win_command: icacls C:\Users\musculus\AppData\Roaming\Microsoft\Credentials /deny Administrator:(F)