# LOGS and Monitoring ==========================================================================================
- name: Install ELK
  hosts: elk_server
  become: yes
  roles:
    - { role: 'elk', tags: 'elk' }

- name: Install log agent on windows vms
  hosts: elk_log
  roles:
    - { role: 'logs_windows', tags: 'agent' }